name: Issue Labeler
on:
  issues:
    types: [opened, edited, pull-request]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v1
        with:
          configuration-path: .github/labeler.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          enable-versioned-regex: true
          sync-labels: true
